### ISSUE TITLE
In Nina the pixel size is displayed incorrectly. (SBIG STF8300M)

### ISSUE THREAD

**Issue by olaf0816** [cedric-r/ASCOM.HomeMade.SBIGCamera#2]
Hi.

First of all I would like to thank you for the great work you have done with the development of this ascom driver.

I have a SBIG STF8300 Mono Camera. While testing your drivers with the astrosoftware N.I.N.A I noticed that the pixel size is displayed incorrectly. After connecting the camera with N.I.N.A a pixel size of 54 micro meter is displayed instead of 5.4 micro meter. Can I change this myself or do you need to change this in your driver program.

BR
Manfred

**Comment by cedric-r** [comment]
Hi Manfred,

This was a mistake I made. I fixed it last week. I forgot to divide by 100. Try the latest version, it should display right.

**Comment by olaf0816** [comment]
Hello.

Thank you for your quick reply. I have tested the new driver and it works fine now. 

Thanks a lot again.

BR 
Manfred
