### ISSUE TITLE
ST-4000 XCM driver voor ASCOM

### ISSUE THREAD

**Issue by Dirkvsam** [cedric-r/ASCOM.HomeMade.SBIGCamera#4]
Hello, 
I was wondering whether the ASCOM.Homemade.SBIGCamera is also usable for ST-4000 XCM?
Thanks in advance for your reaction. 
Regards,
Dirk

**Comment by cedric-r** [comment]
Hi Dirk,
Chances are it is. It should cover most of the common SBIG cameras. But I haven't tested it with that camera.
Give it a go.
Thanks.

**Comment by Dirkvsam** [comment]
Hi Cedric, 

 

Thanks for your fast replay. 

I am going to purchase the camera and give it a try. 

Do you know if it worked for the 2000, I did see something on the forum. 

 

Best regards,

Dirk van Sambeek

 

M: +31 (0)6.11.793.767

E:  ***@***.***> ***@***.***

Parklaan 88 / 3722 BH Bilthoven / Netherlands

 

Van: Cedric Raguenaud ***@***.***> 
Verzonden: dinsdag 24 mei 2022 23:00
Aan: cedric-r/ASCOM.HomeMade.SBIGCamera ***@***.***>
CC: Dirkvsam ***@***.***>; Author ***@***.***>
Onderwerp: Re: [cedric-r/ASCOM.HomeMade.SBIGCamera] ST-4000 XCM driver voor ASCOM (Issue #4)

 

Hi Dirk,
Chances are it is. It should cover most of the common SBIG cameras. But I haven't tested it with that camera.
Give it a go.
Thanks.

**Comment by cedric-r** [comment]
Hi Dirk,

It has. There was an issue with thermal patterns for a while, but I think it's now fixed (yoiu need to freeze the temperature control during exposures with the 2000).

Thanks.
