### ISSUE TITLE
Black guide image from SBIG STXL-11002

### ISSUE THREAD

**Issue by AlvaroFornas** [cedric-r/ASCOM.HomeMade.SBIGCamera#6]
Hi. I've tried your drivers and the image driver works fine but there is no way to get any image from the guiding camera. No error, just a pure black image. Am I doing something wrong?

May be it is related so FYI, I went through these steps

- Working SGP with SGP API Guider
- I installed NINA and the Sbig Tracker driver which I kew was going to break the SGP API guider plugin. This happened always to me and I've found no way to fix it.
- NINA Sbig camera showed some disconnections while in session so I tried your driver
- Homemade driver installed, imaging camera works fine but tracking camera always return a black image in PHD2. When I try the guiding camera in NINA I also get a black image. No errors.

How could I help you to fix this?
Thanks in advance
Alvaro Fornas

**Comment by cedric-r** [comment]
Hi there,
What camera is it? STT?

**Comment by cedric-r** [comment]
Hi there,
I don't know the STXL. Does it have an internal guiding camera? I thought only the STT had one.

**Comment by AlvaroFornas** [comment]
it is a remote guided head. Guiding camera is in the filter wheel, in front of the filters

**Comment by AlvaroFornas** [comment]
Guiding camera is in the filter wheel and it is connected to the camera through a HDMI cable. Here is the product page with the manual so you can see the product. https://diffractionlimited.com/product/fw8s-stxl/

**Comment by cedric-r** [comment]
Ok, so that's similar to the STT. DL say the usb library they made will work will all generations of cameras so it should work.

The driver installs 2 ascom drivers: the imaging driver and the guiding driver. In the ascom preferences of the guiding camera, can you set the debug option? Then look into you app folder and find and send me the sbig ascom  logs?

**Comment by AlvaroFornas** [comment]
Where are those logs stored? thay are not in PHD2 log folder nor in C:\Program Files (x86)\Common Files\ASCOM\Camera\HomeMade SBIGCamera

**Comment by cedric-r** [comment]
Look into c:\Users\XXXXX\AppData\Local\, you'll find a bunch of ASCOM.HomeMade.SBIG*folders
where XXXXX is your windows username. They'll contain the logs I need to try to diagnose the problem.

**Comment by AlvaroFornas** [comment]
Hi Cedric. I've deleted every existing log and set to 'Traced' the guiding driver.
- I've chosen Sbig Imaging Camera in NINA, connected it and take a picture
- Disconnect
- Connect Sbig Guiding Camera in NINA and take a picture. It is completely black
- Disconnected

I've copied every created log and zipped here https://www.dropbox.com/s/0162d29d0dj8b7m/Sbig%20Homemade%20Logs.rar?dl=0

Whatever you need, just ask for it.

Thanks in advance

**Comment by cedric-r** [comment]
Hi there,

I only see the image taken with the guide camera in the logs, but that's the important one. Whats strange is that there is no error recorded anywhere. As far as the driver and the underlying DL library are concerned, everything went well (cooling temperature of -35 degrees though!).

Were you using the camera with some other software before and did it work ok?

**Comment by AlvaroFornas** [comment]
I've never tried your driver before on that system. It actually works on NINA with their native drivers although with random camera disconnections. MaximDL works just fine.

I think I've replicated the problem with MaximDL. In the camera setup I can choose between **internal** and **external** guide chip. Right setup is External, but when I choose Internal, MaximDL also returns a black image like your driver.

![Right](https://user-images.githubusercontent.com/117660034/200542982-8e3cdd1d-6f6c-4a13-9d92-e7d97d7c6b3d.PNG)
![Wrong](https://user-images.githubusercontent.com/117660034/200542989-5bce755c-5e57-4e80-923c-d22d02abd3ad.PNG)

Hope this helps. Obviously Sbig driver has two ways to communicate with their guide chips

**Comment by cedric-r** [comment]
Ah that's interesting. So even though it looks the same as the STT, it doesn't work the same way. I'll see if I can change that.

**Comment by cedric-r** [comment]
I've created a new version that hopefully handles the STX: https://github.com/cedric-r/ASCOM.HomeMade.SBIGCamera/blob/NG/HomeMade%20SBIG%20Camera%20Setup.exe

I don't have an STX or even an SBIG handy to test, so you're the first one.

**Comment by AlvaroFornas** [comment]
How can you be so bloody fast??? Incredible. I'm giving it a try

**Comment by AlvaroFornas** [comment]
- I've unistalled the previous and installed the new one.
- Nina Reports it is the 1.2.3 version.
- Debug trace is activated.
- NINA main camera set as SBIG Guiding Camera
- Unfortunately it returns a black image.
- Logs here: https://www.dropbox.com/s/8pvw63gm1e2bgsi/Sbig%20Homemade%20Logs_02.rar?dl=0
- 
![Sbig Fail](https://user-images.githubusercontent.com/117660034/200551386-269abedd-6440-41cc-9f78-c81d31e8f42d.PNG)

**Comment by cedric-r** [comment]
The guiding camera is still idendified as internal. I must have misidentified the camera type.

**Comment by AlvaroFornas** [comment]
Is it correct to suppose that in a future version internal or external will be selectable in the setup?

**Comment by cedric-r** [comment]
It should be automatic since it won't work with the STXL if the internal tracking chip is selected.

My problem was that at initialisation time, the type of camera isn't available. So I had to delay the chip switch. Try this version: https://github.com/cedric-r/ASCOM.HomeMade.SBIGCamera/blob/NG/HomeMade%20SBIG%20Camera%20Setup.exe

**Comment by AlvaroFornas** [comment]
It works! I'm just now taking a bunch of exposures with guiding and imaging cameras simultanously to check them. I'll keep you informed.

There is something that worries me. Exposures are not constant. If you use only the imaging camera, they are consistent. If you use only the guiding camera, they are consistent. If you use both simultaneously, exposures are no more consistent.

These pictures are inside a closed dome. Guiding bright changes does not bother me too much, but NINA Mean values are inconsistent. In the moment i stop guiding camera, mean values variation is about 200

![exposure03](https://user-images.githubusercontent.com/117660034/200564446-9959cbc3-c375-4cfe-8375-982d0f31b073.PNG)
![exposure1](https://user-images.githubusercontent.com/117660034/200564449-23559cfb-ea18-4684-b7bc-c371a8b09f06.PNG)
![exposure02](https://user-images.githubusercontent.com/117660034/200564452-1ed9a8d6-53d5-4ef6-aee5-fd311e9e0e11.PNG)

I think this is a trickier problem.

and the logs: https://www.dropbox.com/s/j2nnnqedypgbj9b/Unconstant%20exposure%20logs.rar?dl=0

**Comment by cedric-r** [comment]
Strange. It's like there is not enough processing power to process the images. I haven't noticed that. I'll check the logs.

**Comment by AlvaroFornas** [comment]
Computer is not exactly a state of the art machine but this problem only arises with these drivers.

May be it is completely unrelated, but some time ago I tested these drivers on an ST7 camera and something similar happened when guiding and imaging cameras worked together. Imaging camera pictures had some extreme banding, like if about top half of the image was underexposed (or overexposed,do not remember).

**Comment by cedric-r** [comment]
The ST7 works slightly differently from other cameras. When you take an image, you need to freeze the cooler, then unfreeze it. I haven't done that since I never had one. I don't think that's related.

If you make longer exposures for the imaging camera and short ones for the guiding one, does it hapen less?

**Comment by AlvaroFornas** [comment]
I've taken some exposure combinations and transcript the mean values. I can not long exposures because sensor saturates.
Cooler off

guide camera: 1 second     imaging camera binx1: 1 second
Mean values:
3142
3620
3105
3095
3043
3081
3297
3417
3142
3378
3149

guide camera: 1 second     imaging camera binx1: 10 seconds
Mean values:
19412
19414
19496
19387
19637
19330
19007
19080
19323
19465
19265
19623
19063
19133
19356
19793
19770
Guider stopped
19463
19165
18141
18221
19088
Guider disconnected
19199
19233
19294
19189
19180
19229
19067
19122
19080
19215
19232
Guider connected
19212
19189
19149
19115
19062
19148

guide camera: 4 second     imaging camera binx1: 10 seconds
Mean values:
19171
17977
18570
16647
16203
17860
18509
17096
guider stopped
16085
16064
14693 (clouds?)
14373 (clouds?)
15628
16084
14626
16428
16266
14615

I think there are some high clouds that could affect light levels. Not very conclusive.

I'll give it a try on a clear night, check star fluxes and guiding star SNR to have a better understanding. It is possible that these are just fine clouds.

This night is cloudy so we'll have to wait. I'll come back with more data.

**Comment by cedric-r** [comment]
Ok, thanks for testing.

**Comment by AlvaroFornas** [comment]
Hi Cedric.

This night hasn't been the best one but good enough. This is a 3 hour session of 120s exposures with filter V. Guiding exposures of 4 seconds. Data is taken at Binx1 and software binned to 3x as seeing wasn't vey good

First, a flux graph of a non variable star. It show long term varaitions probably to clouds and moon but there is no fast flux variation:

![Flux data](https://user-images.githubusercontent.com/117660034/201037364-cf0a45b1-ecd3-48e4-a1e8-e4a93a464b9d.PNG)

and now the relative photometry of V1109 CAS:

![Var 1109 CAS](https://user-images.githubusercontent.com/117660034/201037467-cda9c3ba-a316-472e-8024-7421e29d73bf.PNG)

I think the drivers perform pretty well. Thanks for your work, you have extended the camera life well beyond SBIG expectations. I'm really grateful, thank you.

Best regards
Álvaro Fornas

**Comment by cedric-r** [comment]
Hi Alvaro,

Glad it helps you.
