### ISSUE TITLE
Simultaneous download from main and guider camera problem. Sbig STXL-11002

### ISSUE THREAD

**Issue by AlvaroFornas** [cedric-r/ASCOM.HomeMade.SBIGCamera#7]
Hi Cedric. I've been testing your driver and I've come with an unexpected problem. When main camera is reading an image and the guider tries also to read, guider image is just noise. What baffles me is that PHD2 Guiding goes wild without reason. This is a frame error that happened at 19:51:16
![guide error at 19 51 16](https://user-images.githubusercontent.com/117660034/201541934-87bd8473-904a-4b83-881a-ab8c7eec3020.PNG)

Here are the logs. a lot of files. I suppose it is because I had Trace enabled 
https://www.dropbox.com/s/z9o1b11uduaiseo/Logs.rar?dl=0

**Comment by cedric-r** [comment]
Hi there.
I can see where there could be a bottle neck since the usb library isn't reentrant. So I have to lock the calls until the previous one is completed. I've seen the snow screen on my STT once in a while, but it has never been a problem with phd: phd finds no star in the snow, and resumes guiding on the next image. I'm really surprised by how it affects your guiding. Could you be using a very large search box in your settings that results in phd picking a different star on the next frame?

**Comment by AlvaroFornas** [comment]
search box is the default, 15 may bePHD Search region is 15, the default one. I've seen that snow screen also with SGP but I never saw it on MaximDL.

What is really new and a problem is the guiding. There was no dithering and deviation is always on the same direction. I'm using TheSkyX ascom driver and I really do not trust him. With SGP I always used the Ascom Device Hub but now, with NINA, Meridian flip fails.

May be there is nothing you can do as your driver obiously isn't moving the mount and a snow screen shouldn't me a problem.

**Comment by cedric-r** [comment]
If you look at the guide star before and after the snow screen, do you see it move? What's surprising is that the amount the guide star seems to have moved is very similar, if not constant. A really, really bad polar alignment could move the guide star of a similar amount between 2 images, but that sounds really unlikely to be your problem. Also the snow screen normally happens a few times per night when several calls I made to the camera at the same time and one ends in timeout, not regularly like in your graph.

I wsee nothing in the logs that would explain any issue.

**Comment by AlvaroFornas** [comment]
When the guide image recovers, the star has moved. Polar align is good. This camera takes some time to read an image. If I guide with 1s exposures and the main camera takes binx1 images, I for sure get the snow guide image.

I'll continue testing and keep you informed but here we are going to have clouds for several days.

**Comment by AlvaroFornas** [comment]
Hi Cedric. I think I've somewhat resolved the problem. When a noisy guide image arrives to PHD2, it detected a false star away from the original. Good darks, low star mass tolerance and subframe region have almost resolved the problem.

Thank you

**Comment by cedric-r** [comment]
Hi Alvaro,

That would certainly explain it. If phd picks noise as a star, it will do strange things.
Thanks for testing that.
