### ISSUE TITLE
SBIG STXL-11002 guide camera shouldn't be cooled

### ISSUE THREAD

**Issue by AlvaroFornas** [cedric-r/ASCOM.HomeMade.SBIGCamera#8]
Hi Cedric, I've noticed something strange with these drivers. SBIG STXL-11002 has an external guider camera (it is on the filter wheel) that isn't cooled but PHD2 thinks it is cooled

![Cooling](https://user-images.githubusercontent.com/117660034/202892540-b13a5a21-fa1a-42db-8e57-3b25b5a2668d.png)

If I deactivate the cooler on PHD2, it also gets deactivated in the NINA imaging camera. They share cooler controls.

Not really sure how PHD2 manages cooling but I've got several imaging session in which at some point cooler is set off and I think it is PHD2 swithing it off. SBIG STXL-11002 Guide Camera driver should report it has no cooling capabilities.

Also, I think guiding camera has no temperature sensor. Don't know where is driver getting it from. Guide temp doesn't match perfectly with the main imagin camera temp. May be both are read at different instants.

Hope it helps

Regards
Alvaro Fornas

**Comment by cedric-r** [comment]
Ah yes, that would make sense: they can share the cooler if SBIG wanted to cool the guiding sensor, or maybe it doesn't actually have one, even though it looks like it does. I think I'll deactivate the cooling controls for the guiding sensor and let it follow the main cooling system.

**Comment by AlvaroFornas** [comment]
I'm pretty much certain that this camera has no cooling. I've never seen those controls on MaximDL, it only connection is a DVI cable FW<-->Camera and, in the manual, there is nothing about cooling. https://diffractionlimited.com/wp-content/uploads/2016/08/stt_filterwheel_manual_080812.pdf

![MaximDL Cooler](https://user-images.githubusercontent.com/117660034/202897129-11d5b1cf-8e5a-42fd-9fc3-a3c2e5bb1422.PNG)

About the snowy guiding images, is there a way to discard them from the driver? I don't know under which conditions they happen, but something like if you detect it is going to be snowy, return a black image, for example. The idea is not to feed garbage to the guider.

Thanks in advance, like always
Alvaro Fornas

**Comment by cedric-r** [comment]
Hi Alvaro,

Try this version: https://github.com/cedric-r/ASCOM.HomeMade.SBIGCamera/blob/NG/HomeMade%20SBIG%20Camera%20Setup.exe

it should disable the cooler for the guiding sensor.

I haven't found the cause of the snow screen yet, still looking into it. Debugging ASCOM isn't easy.

**Comment by AlvaroFornas** [comment]
It seems to work perfectly!! now PHD present the cooling checkbox as greyed. In the logs PHD complains because it says it has cooler but can not get the temperature. Don't know if it matters a lot or not:

15:45:52.705 00.003 5352 Connecting to camera [ASCOM SBIG Guiding Camera Driver] id = []
15:45:52.708 00.003 5352 Create ASCOM Camera: choice 'ASCOM SBIG Guiding Camera Driver' progid ASCOM.HomeMade.SBIGGuidingCamera
15:45:52.790 00.082 5352 setting camera Name = ASCOM driver for SBIG cameras
15:45:52.797 00.007 5352 ASCOM camera: MaxBinning is 3
**15:45:52.801 00.004 5352 ASCOM camera: has cooler**
15:45:52.807 00.006 5352 ASCOM Camera: set binning = 1
15:45:52.827 00.020 5352 GetDouble("/profile/2/camera/pixelsize", 0.000000) returns 7.400000
15:45:52.831 00.004 5352 DoConnectCamera: reconnecting=0 warningIssued=0 lastCam=[ASCOM SBIG Guiding Camera Driver] scaleRatio=1.000
15:45:52.834 00.003 5352 Connected Camera: ASCOM driver for SBIG cameras
15:45:52.838 00.004 5352 FullSize=(0,0)
15:45:52.841 00.003 5352 PixelSize=7.40
15:45:52.844 00.003 5352 BitsPerPixel=16
15:45:52.847 00.003 5352 HasGainControl=0
15:45:52.850 00.003 5352 HasShutter=1
15:45:52.854 00.004 5352 HasSubFrames=1
15:45:52.857 00.003 5352 ST4HasGuideOutput=0
15:45:52.860 00.003 5352 GetBoolean("/profile/2/camera/AutoLoadDefectMap", 1) returns 1
15:45:52.864 00.004 5352 auto-loading defect map
15:45:52.880 00.016 5352 Loading defect map file C:\Users\Admin\AppData\Local\phd2\darks_defects\PHD2_defect_map_2.txt
15:45:52.883 00.003 5352 Defect map file not found: C:\Users\Admin\AppData\Local\phd2\darks_defects\PHD2_defect_map_2.txt
15:45:52.887 00.004 5352 Status Line: Defect map not loaded
15:45:52.892 00.005 5352 GetBoolean("/profile/2/camera/AutoLoadDarks", 1) returns 1
15:45:52.896 00.004 5352 Auto-loading dark library
15:45:53.077 00.181 5352 loaded dark frame exposure = 1000, med = 1358
15:45:53.133 00.056 5352 loaded dark frame exposure = 1500, med = 1359
15:45:53.166 00.033 5352 loaded dark frame exposure = 2000, med = 1358
15:45:53.213 00.047 5352 loaded dark frame exposure = 2500, med = 1359
15:45:53.249 00.036 5352 loaded dark frame exposure = 3000, med = 1359
15:45:53.297 00.048 5352 loaded dark frame exposure = 3500, med = 1359
15:45:53.332 00.035 5352 loaded dark frame exposure = 4000, med = 1359
15:45:53.380 00.048 5352 loaded dark frame exposure = 4500, med = 1360
15:45:53.415 00.035 5352 loaded dark frame exposure = 5000, med = 1360
15:45:53.473 00.058 5352 loaded dark frame exposure = 6000, med = 1360
15:45:53.476 00.003 5352 loaded dark library from C:\Users\Admin\AppData\Local\phd2\darks_defects\PHD2_dark_lib_2.fit
15:45:53.479 00.003 5352 Status Line: Darks loaded
15:45:53.484 00.005 5352 DarkLib check: undefined frame size for current camera
15:45:53.492 00.008 5352 Status Line: Camera Connected
15:45:53.505 00.013 5352 invoke: [80020009] Ocurrió una excepción.
**15:45:53.509 00.004 5352 ASCOM error getting CCDTemperature property:**
(ASCOM.HomeMade.SBIGGuidingCamera) Method Cooler not implemented on guiding sensor is not implemented in this driver.

**Comment by cedric-r** [comment]
Ok good. I didn't know if I had to raise an exception if the client requested the temperature even though it was told before that it's not implemented. It looks like phd does that.

**Comment by AlvaroFornas** [comment]
I've misunderstood something. In the log PHD thinks that camera has a cooler:
15:45:52.801 00.004 5352 ASCOM camera: has cooler

is that right?

**Comment by cedric-r** [comment]
I just spotted that. I don't know why it says the camera has a cooler. Phd2,s code says it gets it from the CoolerOn call:
   HasCooler = false;
    if (driver.GetProp(&vRes, L"CoolerOn"))
    {
        Debug.Write("ASCOM camera: has cooler\n");
        HasCooler = true;

But I return false for the guiding camera:
       public override bool CoolerOn
        {
            get
            {
                debug.LogMessage("CoolerOn", "Get");
                return false;
            }

 So that shouldn't happen.

**Comment by cedric-r** [comment]
I use Phd so I'll experiment with that.

**Comment by AlvaroFornas** [comment]
Hi Cedric. I'm trying the new drivers and, after losing the star (clouds) I got this error:

8:14:23.998 00.004 3752 Saturation detection set to Max-ADU value 65535
18:14:24.021 00.023 3752 putprop: [80020009] Ocurrió una excepción.
18:14:24.025 00.004 3752 ASCOM error turning camera cooler off:
(ASCOM.HomeMade.SBIGGuidingCamera) Method Cooler not implemented on guiding sensor is not implemented in this driver.
18:14:24.028 00.003 3752 Alert: ASCOM error turning camera cooler off:
(ASCOM.HomeMade.SBIGGuidingCamera) Method Cooler not implemented on guiding sensor is not implemented in this driver.
18:14:24.255 00.227 3752 camera cannot set cooler temperature
18:14:24.261 00.006 3752 invoke: [80020009] Ocurrió una excepción.
18:14:24.264 00.003 3752 ASCOM error getting CCDTemperature property:
(ASCOM.HomeMade.SBIGGuidingCamera) Method Cooler not implemented on guiding sensor is not implemented in this driver.

BUT, as PHD2 can not set the temperatures, imaging camera on NINA continue cooled. For now it looks an annoying message on PHD2

**Comment by cedric-r** [comment]
Try this version: https://github.com/cedric-r/ASCOM.HomeMade.SBIGCamera/blob/NG/HomeMade%20SBIG%20Camera%20Setup.exe

I raise an exception when phd asks for cooler. that seems to make it understand that there isn't one, so hopefully it won't try to talk to it.

**Comment by AlvaroFornas** [comment]
Previous version was operating right except for the error message.

It is cloudy so I cannot test the new version 1.2.9, I've only able to connect it. Log content is:

19:42:19.809 00.003 2024 Connecting to camera [ASCOM SBIG Guiding Camera Driver] id = []
19:42:19.812 00.003 2024 Create ASCOM Camera: choice 'ASCOM SBIG Guiding Camera Driver' progid ASCOM.HomeMade.SBIGGuidingCamera
19:42:19.862 00.050 2024 setting camera Name = ASCOM driver for SBIG cameras
19:42:19.870 00.008 2024 ASCOM camera: MaxBinning is 3
19:42:19.876 00.006 2024 invoke: [80020009] Ocurrió una excepción.
19:42:19.880 00.004 2024 CoolerOn:
(ASCOM.HomeMade.SBIGGuidingCamera) CoolerOn not implemented on guiding sensor is not implemented in this driver.
19:42:19.883 00.003 2024 ASCOM camera: CoolerOn threw exception => no cooler present
19:42:19.889 00.006 2024 ASCOM Camera: set binning = 1

And PHD2 GUI doesn't offer anymore de cooling options.

![Cooling](https://user-images.githubusercontent.com/117660034/202922735-6414e6b7-4c3d-4337-aef2-20ccac7cbe54.PNG)

I'll try this version and report any news. I think you have nailed it.

As a side note, in NINA when cooler is off it shows 1 temperature. 

![Cooler off](https://user-images.githubusercontent.com/117660034/202922918-e2f42981-1bc9-49a0-bb4d-9636be444c80.PNG)

But with the cooler on, it shows 2

![Cooling NINA](https://user-images.githubusercontent.com/117660034/202922963-6ae28017-923f-4a68-84d7-f3d8bb06cb41.PNG)

MaximDL with native drivers also showed a fake temp for the guiding so it seems irrelevant.

**Comment by cedric-r** [comment]
I think the 2 temperatures are the current sensor temperature and the target temperature.

**Comment by AlvaroFornas** [comment]
When it is warming it looks to be a target temperature of 20ºC, but when it is cooling it follows the imaging camera temp in integer values. Unless it is a symptom of a problem, I can live with it

![cooling](https://user-images.githubusercontent.com/117660034/202925874-10cc9fc3-02c1-41bf-880d-95b468eb4444.PNG)

**Comment by cedric-r** [comment]
That's normal in Nina: when cooling the temperature on the right is the target. It goes down based on your final target temperature and the time you allocated. The temperature on the left is the actual temperature of the sensor trying to reach that target. It should follow a similar pattern when warming up in the other direction. It's entirely managed by Nina.

**Comment by AlvaroFornas** [comment]
I had no idea it worked that way. Thanks for the explanation. I'm testing again, let's cross fingers

**Comment by AlvaroFornas** [comment]
Hi Cedric. Camera has been working right for some hours and it looks there are no more problems with the cooler.

AFAIK, the only remaining problem is the snowy guiding frames. I've taking a lot of frames at binx3 (fast read) and guiding at 4s exposures has been nice, but when I've changed to imaging at binx1 I've had problems. Every image takes several seconds (8?) to download so, an imaging frame download time is always longer that a guiding exposure. So I always get an snowy guiding image. When this happens, PHD2 behaves in 2 possible ways:
- He thinks he has found a fake star in the snowy image and guiding goes wild for a moment. It also can lose the guiding star.
- He finds no star and begin the finding star and settling procedure, which takes some time on every frame

Do you have an idea of how to tweak PHD2 to avoid the snowy frame effects? Star mass detection Tolerance has no effect as PHD2 does not report a significant change in star mass when it picks a fake star on an snowy frame. Decreasing guiding agressiveness also doens't help (?)

Hope you can solve this question as I understand you can reproduce it on your camera.

Edit: With 8s guiding exposures there are almost no snowy frames. Whith 4s guiding exposures, snowy frame appeared every time. I've spotted several concurrent downloading with no snowy frames. Ni idea of what happens.

Regards
Alvaro Fornas
